/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Hosts {
  avatar_url: string | null;
  id: Generated<number>;
  name: string;
}

export interface Images {
  alt: string | null;
  id: Generated<number>;
  listing_id: number;
  url: string;
}

export interface Listings {
  category: string;
  created_at: Generated<Timestamp>;
  description: string;
  host_id: number;
  id: Generated<number>;
  location: string;
  price_per_guest: Numeric;
  title: string;
}

export interface DB {
  hosts: Hosts;
  images: Images;
  listings: Listings;
}
